name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        if: ${{ github.event_name =='push' }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "redux-anecdotes"
          heroku_email: "ptcebula@gmail.com"
          healthcheck: "https://redux-anecdotes.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
  
  semantic_versioning_tagging:
    needs: deployment_pipeline
    if: ${{ github.event_name =='push' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: bump version and push tag
        uses: anothrNick/github-tag-action@cfd2c75d0bf1071c5355d577f0018b0e1b515e9c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      
